### ISSUE TITLE
gns3 3.0 documentation

### ISSUE THREAD

**Issue by josephmhiggins** [mother/gns3-docs#67]
okay, I figured it out.
The gui documentation has to be largely based on the buttons in the gui.
The "two" easiest chapters are:
Projects
    import project, and
    export project;
Help
    looking at gns3*.log
    looking at virtualbox community pages
    looking at vmware webpages

It will be very difficult to understand for a non-Microsoft Word user to understand, but the classes in VBA should be designed around the buttons. The big problem with Word is that the easiest to learn and the fastest to learn is to create code around the Editing button - Replace. It creates a total mess.

The documentation, save the install procedures, should be designed around, based upon, the gns3 developer buttons.

The installation documentation is somewhat different.
If you look at the gns3 python code, and the best example is the gns3 developers use a stopwatch of 120 seconds to verify the gns3 vm is online, the gns3 developers are verifying that some event (it is an Event and not a simple log entry - but that is another story), has occurred. That means the installation instructions **must** verify that the event has succeeded. That means that chapter of installation **must** include verification and those **instructions** must not be in the Help section.

I think that is good.

Edit: The Project Chapter does not exist in the gns3 documentation. But...there may be some kind of bug in the way gns3 projects are exported: 
https://gns3.com/community/featured/error-while-exporting-a-projcet
I do not know what is going on with export project problems. It might be over my skill level.
But the chapter is wide open for the taking. I think I will take it.

**Comment by eantowne** [comment]
This is something that I have been tossing around in my head for some time now. A significant portion of the 2.x documentation is still relevant for 3.x. There are 2 major portions that are a point of divergence:

- Installation
- Administration - Specifically RBAC and it's implications, as well as controller/compute management

Additionally, some portions of the more tutorial based sections will need 3.x specific versions such as importing appliances.

There are a few improvements that I think may be viable for the overall structure as well logical flow from subject-to-subject as well as additional topics that could be covered.

I think it would be good to provide a couple of different versions of an outline for Jeremy to consider.

Thoughts?

**Comment by josephmhiggins** [comment]
Jeremy used the term "hidden" in his interview with Bombal on one of the major.minor gns3 versions, i think 2.2.
I use the term "deprecated". VPCS is a perfect of example of what should be hidden in a new tab on the gns3.com documentation webpage that should be labeled Deprecated. I would leave all that stuff there and not even try to fix it.

Yeah...Installation and "Administration" - maybe features and Administration falls under Features.
My Button idea looks to be dead on.
I will look tomorrow.
There should be some type of Python class or module thing that is named
Project
I am hoping that I am correct and the class/module will have at least these methods
SaveAs
Export
Import
Open
New

and I do not know what those Edit and Delete things are - I never used them.

Then I can just regex the entire source code with powershell and grab all the missing Documentation and put it in a spreadsheet.

**Comment by josephmhiggins** [comment]
However, there is no telling what type of github/visual studio code tools the gns3 have at their disposal; they probably already have something like that.
