### ISSUE TITLE
Debian based instructions mixed in with Arch based instructions

### ISSUE THREAD

**Issue by eantowne** [mother/gns3-docs#68]
This section: https://docs.gns3.com/docs/getting-started/installation/linux#install-gns3-from-pypi, includes instructions for using `apt`. This section is a sub-section under the Arch instructions (not compatible) found here: https://docs.gns3.com/docs/getting-started/installation/linux#install-gns3-on-archlinux-based-

My guess is that the PyPi instructions were meant to have a different header type.

**Comment by rflandau** [comment]
I just submitted a PR to correct the Debian instructions and remove the PyPi instructions at the foot.
#86

**Comment by grossmj** [comment]
Changes are now online. Thanks :+1:
