### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by holmanb** [mother/gns3-docs#7]
I found two broken links on the gns3 docs website.  The last two links on the following page produce a 404 error.  It looks like at least one of them may have been just moved so I'll take a look and probably propose a fix.  

https://github.com/mother/gns3-docs/blob/master/docs/getting-started/installation/remote-server.md

**Comment by holmanb** [comment]
I really hope this is the correct repo for the gns3 docs site.  I had to do a little bit of digging and I have no clue what "mother" or "docusaurus" are, but this appears to correspond to the gns3 docs site so I assume if I'm wrong that someone here can point me in the correct direction.

**Comment by holmanb** [comment]
I believe these are the required fixes, PR incoming:

https://github.com/mother/gns3-docs/blob/master/docs/getting-started/installation/one-server-multiple-clients -> https://github.com/mother/gns3-docs/blob/master/docs/getting-started/installation/one-server-multiple-clients.md

https://github.com/mother/gns3-docs/blob/master/docs/getting-started/how-to-guides/configure-gns3-to-use-an-additional-remote-server ->
https://github.com/mother/gns3-docs/blob/master/docs/how-to-guides/configure-gns3-to-use-an-additional-remote-server/

**Comment by bajtekv** [comment]
Read this documentation for download links. _https://docs.gns3.com/1Bn-s1Izkjp13HxcPF4b8QSGfkWJYG_dpMt9U1DQjvZ4/index.html_ CHECKLINK

**Comment by holmanb** [comment]
> Read this documentation for download links. _https://docs.gns3.com/1Bn-s1Izkjp13HxcPF4b8QSGfkWJYG_dpMt9U1DQjvZ4/index.html_ CHECKLINK

The webpage contains the following message:
```
Page Not Found

We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
```

**Comment by eantowne** [comment]
Thank you, I will take a look at these this week.
